version: '3'

services:

  db-postgres:
    restart: on-failure
    build:
      context: .
      dockerfile: devops/postgres.dockerfile
    command: postgres -c 'max_connections=500'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=jaspion_db
      - TZ=GMT

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 10

  api-auction:
    build:
      context: .
      dockerfile: devops/Dockerfile
    ports:
      - "8099:8099"
    environment: 
      - ENVIRONMENT=PRD
      - DB_HOST=db-postgres
      - DB_PORT=5432
      - DB_NAME=jaspion_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=test
    depends_on:
      - db-postgres
    links:
      - db-postgres
      


